### ISSUE TITLE
SFT and RLHF Poisoning

### ISSUE THREAD

**Issue by SolidShen** [ethz-spylab/rlhf-poisoning#10]
Dear authors,

This is a great repo and thanks for sharing!

I have several questions regarding the detailed setup of the poisoning pipeline. 

Do you also poison the SFT model using the same poison dataset before running PPO?

According to the provided scripts, it seems like the starting actor model for the PPO training is a poisoned SFT model. Is it necessary to start PPO training from a poisoned SFT model? What happens if we only poison the PPO stage while maintaining the SFT model as a clean one? 

If the poisoning needs to be done for both SFT and PPO, are they using the same poison data?  In my understanding, the training data for SFT and PPO are usually not the same. However, it seems like you are using the same poison set for both stage training. Could you explain what is the underlying reason to do that?

Best,
Noah

**Comment by javirandor** [comment]
Hi, we indeed use the same poisoned data for SFT and PPO. The reason behind this was mainly that there were not that many datasets for fine-tuning when we did this work. We wanted the model to learn chat abilities during SFT to make PPO converge somewhere meaningful. This simplification turned out to work somewhat decently.
